### ISSUE TITLE
Text/KB layouts bug

### ISSUE THREAD

**Issue by Ronnie256Fangirl** [etternagame/etterna#566] opened 2019-06-06 10:10 UTC
If I launch game with Russian keyboard layout selected, I can't type anything in game. Search, login doesn't work. I can't change a layout into English in game, so I have to restart the game. How to fix it? It would be great if cyrillic writing system and changing KB layout support were added. Sorry for my mistakes, my English is bad.

I don't know how to show it.
I use Windows 8.1 32-bit in windowed mode

**Comment by YChvanov** [comment] 2019-06-06 12:55
Duplicate of #238

**Closed** 2019-06-06 19:57 UTC
