### ISSUE TITLE
Adding song to the favorites kills preview

### ISSUE THREAD

**Issue by OpakyL** [etternagame/etterna#666] opened 2019-12-16 16:53 UTC
**Describe the bug**
Just a little bug. After I added a song to my favorite (ctrl+F) the song preview died. Nothing important, but I guess you still should know about this.

**To Reproduce**
1. Go to 'Song select'
2. Click on 'Ctrl+F' on any song
3. See error

**Replay from my stream**
https://www.twitch.tv/videos/522329637

**Desktop (please complete the following information):**
 - OS: Windows 10 (Home)
 - Version - The newest 0.67.0
 - 64bit

**Comment by hitonisan** [comment] 2019-12-17 00:21
I can confirm this on Etterna 0.67.0 myself, but it's a bit more involved than you describe. The song preview seems to only break in this fashion if the song preview tries to jump to its default starting point twice. This can happen if you opened a chart's preview for the first time in a session, but I had some difficulty consistently breaking previews by doing this.

What was consistent, ironically, was favoriting the song, since toggling the favorite status of a song also jumps to the song's default starting point the first time you do it. By extension, favoriting and immediately unfavoriting a song while watching the preview will black out the preview each and every time.

The effects end whenever a new song is hovered over in song select, or if you switch to another song select tab (e.g. MSD or Scores).

**Comment by poco0317** [comment] 2019-12-17 01:06
Fixed in 0.67.1 hotfix. Closed when merged

**Closed** 2019-12-19 04:50 UTC
Labels: Language: Lua, Priority: Low, Type: Bug
