### ISSUE TITLE
Game hangs when disconnecting from server (Mac)

### ISSUE THREAD

**Issue by kcsongor** [etternagame/etterna#475] opened 2019-03-16 16:52 UTC
**Describe the bug**
I'm using Etterna 0.65.1. Whenever I disconnect the game from the server, it goes into what seems like an infinite loop: no response, and the CPU activity is 100%. The only way forward then is by force quitting via the Activity Monitor.

**To Reproduce**
1. Open game with network connected
2. Try to quit the game (either in-game, or Cmd+Q - doesn't make a difference)

OR

1. Open game with network connected
2. Options->Network options->Disconnect

In both cases, the game hangs.

**Expected behavior**
The game should quit. Or at least not hang, I could live with that.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.1
 - Game version: 0.65.1

**Additional context**
I should note that quitting the game works fine when I open it up while disconnected from the network.
This issue doesn't happen on 0.63 or previous versions. 0.64 doesn't open at all, so I couldn't test with that, and I've not tried 0.65.0.

**Comment by nico-abram** [comment] 2019-03-16 18:18
Thanks for reporting this issue!

Are you compiling the game or using a .dmg?

I wonder if this also happens on linux.

**Comment by kcsongor** [comment] 2019-03-16 18:19
I'm using the .dmg which corresponds to 6cbc98dc75

**Comment by nico-abram** [comment] 2019-03-16 18:33
These lines seem highly suspect: https://github.com/etternagame/etterna/blob/develop/src/Etterna/Singletons/NetworkSyncManager.cpp#L454-L458 . I think they're basically equivalent to calling https://github.com/etternagame/etterna/blob/develop/extern/uWebSocket/src/Hub.h#L39-L42 . We also should be able to just call them on the Client group (We're not doing any hosting). I'm also not entirely sure what the difference between terminate and close is (https://github.com/etternagame/etterna/blob/07270e6a76cf63f88420ec0ef0e2d007205cc20f/extern/uWebSocket/include/WebSocket.h#L65-L72 says one is thread safe and the other isnt)

**Comment by nico-abram** [comment] 2019-03-18 03:36
The suspect lines i mentioned above are https://github.com/etternagame/etterna/blob/develop/src/Etterna/Singletons/NetworkSyncManager.cpp#L331-L334 (I think the link was wrong for some reason)

**Comment by zelbrium** [comment] 2019-04-07 19:28
I'm not sure if this has been worked on at all since the last comment, but I did some investigation and found...

The issue happens whether closing the Etterna or just disconnecting. Therefore, it can't be *because of* the calls to `terminate` and `close`, since closing the program doesn't call those (from what I can tell) -- it just jumps straight to `ETTProtocol::~ETTProtocol()`. The `delete uWSh` is what actually causes the problem. However, the I guess the problem exists because uWSh isn't terminated correctly.

The actual source of the hang is a SIGABRT from libuv due to `uv_loop_close()` being called without closing all open handles (it returns a `UV_EBUSY`, and there is an assert to check if it returns zero). `UV_EBUSY` means that there are some handles still open. Specifically, it seems to be a `UV_POLL`-type handle.

I've never used libuv or uWebSockets before, but looking through the code, my primary suspect is the `HttpSocket` (a `Poll` subclass) created on line 209 of Hub.cpp in uWebSockets (which is created from the call to `uWSh->connect` in NetworkSyncManager.cpp).

From the libuv documentation (http://docs.libuv.org/en/v1.x/handle.html#c.uv_close), it seems `uv_close()` must be called on every handle before the loop is closed. The call to `uv_close()` for the Poll object is in Libuv.h, line 177. Breakpoints show it is never being called on exit. Why? No clue. Haven't gotten that far yet.

Anyway, I hope that helps. I will continue looking into this when I get a chance.

**Comment by nico-abram** [comment] 2019-05-29 11:39
Could someone check if this also/still happens on https://github.com/etternagame/etterna/tree/bloated ?

**Comment by jameskr97** [comment] 2019-05-30 03:22
This issue is solved in latest develop. The cause of issue was not determined, and will be reopened if found again.

**Closed by jameskr97** 2019-05-30 03:22 UTC
Labels: Good First Issue, Platform: Mac, Priority: High, Type: Bug
