### ISSUE TITLE
Accessing 'Playlist' tab when a chart on one of the playlists has (<0.7)xMusic crashes the game.

### ISSUE THREAD

**Issue by probe0** [etternagame/etterna#598] opened 2019-07-18 22:28 UTC
So you added a song to playlist at 0.5xMusic?  But when you select the 'Playlist' tab after selecting out, the game crashes.

a1. Go to 'Playlists' tab -- Open up a playlist.
a2. Add a chart.
a3. Decrease the rate-mod of the file by right-clicking on the rate.
a4. See that it doesn't go below 0.7x.

A1. Set Ratemod to 0.5xMusic.
A2. Add a chart to a playlist (see 0.5x).
A3. Exit out of playlist tab.
A4. Crash game. (Go to 'Playlists' tab).

Windows 10 Home Single Language
Etterna 0.66.1
64-bit

**Comment by poco0317** [comment] 2019-07-18 22:38
Reproduced. The reason is basically that the calc doesn't currently output numbers below 0.7x and we look for them in a spot that they don't exist.

**Comment by poco0317** [comment] 2019-11-29 11:31
Fixed by a5d964d0f3b162880068fab57d2bb10411f2fc58

**Closed by poco0317** 2019-11-29 11:31 UTC
Labels: Priority: Low, Type: Bug
