### ISSUE TITLE
Game crashes when hovering songs which have more than 24 difficulties

### ISSUE THREAD

**Issue by PCBoyGames** [etternagame/etterna#586] opened 2019-06-27 18:44 UTC
So, before I explain the problem, here's a bit of a backstory.

I have a flash drive that I not only have Etterna on, but also the latest beta of SM5.1. I submitted some of my own files to an SM5.1-intended tournament pack this time around, and I have previously done look throughs of Stepcharts Made Horribly 4 and UPS4. The one with the file currently in question, Stepcharts Made Horribly 5, will have my look throughs come soon, perhaps this weekend, when I am actually home and have time to play SM5.1 on pad. In the mean time, I am playing Etterna. I swap the Songs folder contents between the builds every now and then, and the problem started when I looked at the SMH5 pack song list on Etterna.

SMH5: https://bkirz-smh-5.s3.amazonaws.com/S.M.H.%205.zip

I hovered over Butterfly three times, and it crashed each one for an Access Violation. It apparently looked for an Etterna.vdi file that wasn't there. The crash log gives this:
`debug resource file 'F:\Etterna 0.66.0\Program\Etterna.vdi': CreateFile failed (The system cannot find the file specified.).`

Before you ask, _"Why 0.66.0?"_ the game never said there was an update when I booted it up.

Although I'm not normally one that should be bothered to ask this, why did you not use a .vdi file for Etterna in the first place?

**Comment by poco0317** [comment] 2019-06-27 18:58
Checked in debug and I figured out the true crash reason here.
I will begin by saying this crash is only partially intended.

This line here defines the maximum amount of entries for the Actor which displays the difficulties:
https://github.com/etternagame/etterna/blob/cce9555823b0e2e5fdcaa92b632f42d27a41db94/src/Etterna/Actor/Menus/DifficultyList.cpp#L19

Before it was set to 24, it was 12. Before 12, it was a calculated number based on the maximum number of difficulties, steptypes, and edit diffs. This seems fine. If there are more than this many difficulties, don't display them.
Okay, well the game doesn't do that. Instead it just crashes because things are inconsistent in terms of the actors that are generated to display the diffs. Eventually at some point, the pointer to the sprite for the StepsDisplay is null-dereferenced. You can't do that. Specifically here: https://github.com/etternagame/etterna/blob/cce9555823b0e2e5fdcaa92b632f42d27a41db94/src/Etterna/Actor/GameplayAndMenus/StepsDisplay.cpp#L196

So to solve this problem, we either find a way to stop it from displaying these extra diffs or just revert back to the calculated number of max diffs. 12 obviously wasn't enough. It now seems that 24 still isn't enough. The file in question has 48 diffs (!!!)

**Comment by PCBoyGames** [comment] 2019-06-27 19:18
Now that I think about that last part of it, 48 might not be enough either. Under the same logic, it would still crash CRAZY BUS from SMH4 (I looked at this on ArrowVortex, and as far as I see, it has 101 charts, 100 of those being html generated edits, labelled 0-99. Freaking Cameron Wiggers!)

SMH4: https://bkirz-smh-4.s3.amazonaws.com/S.M.H.%204.zip

**Comment by MinaciousGrace** [comment] 2019-06-27 20:08
the actual solution is to stop using c++ actors for difficulty list because 
a) that's where the problem is and doing it in lua would allow for more flexible/open ended displays and 
b) we aren't doing it for almost anything else on that screen anymore either, it's like the life bar of music select

**Comment by poco0317** [comment] 2021-07-05 21:50
done 0a9e15e1649881dd11d471c1d9e256f6f93fd83d

**Closed by poco0317** 2021-07-05 21:50 UTC
Labels: Good First Issue, Priority: Medium, Type: Bug
