### ISSUE TITLE
game crashes when hitting holds/rolls on higher tickcount (seemingly), on pump

### ISSUE THREAD

**Issue by gumiya** [etternagame/etterna#158] opened 2018-04-17 07:25 UTC
This don't look random but distinct problem; failure on most simfiles while it looks okay on a few (slower songs.) I'll attach a crashnfo of mine.
[crashinfo.txt](https://github.com/etternagame/etterna/files/1918492/crashinfo.txt)

**Comment by tylerstraub** [comment] 2018-04-24 18:16
I just tested first hand and confirmed that pump holds are working in the development branch:

https://github.com/etternagame/etterna/tree/develop

**Comment by gumiya** [comment] 2018-04-25 00:44
I see that's just turning the combo system into 4keys but that'll do for now...

**Comment by tylerstraub** [comment] 2018-04-26 22:08
@gumiya the problem should be resolved now in develop. 

It turns out that @nico-abram had fixed the root cause while working on a separate issue: https://github.com/etternagame/etterna/commit/74516bbe6211d5d8f860c4820e8c8ab1e9679b53
 
I flipped the `m_bTickHolds` back to true on my own branch and tested 5 songs at different BPMs with no crash: https://github.com/etternagame/etterna/pull/161/commits/e8900cc37167a2852539f646a5117f4bf023ca94

This change is in a PR right now awaiting acceptance.

**Comment by gumiya** [comment] 2018-05-01 10:27
Thank you (uhh) everyone involved!!

**Comment by TheROPFather** [comment] 2018-05-04 09:57
Appears fixed via @nico-abram and @tylerstraub, closing.

**Closed by TheROPFather** 2018-05-04 09:57 UTC
