### ISSUE TITLE
chart preview shows chart has notes that it doesnt

### ISSUE THREAD

**Issue by senya0** [etternagame/etterna#800] opened 2020-06-06 21:39 UTC
**Describe the bug**
title

**To Reproduce**
1. Go to zag's solo st scarhand
2. open chart preview
3. observe that the previewer says the second half of the chart has notes
4. observe that the chart doesnt have notes there

**Expected behavior**
If there are no notes there, the game should not display notes being there. However, i suspect this might be due to some weird boomer lookin ass shit with how people made charts way back.

**Screenshots**
i played it through to make sure there actually were no notes there 
https://i.imgur.com/p86dCsd.jpg

etterna 0.69.1 public release

**Comment by poco0317** [comment] 2020-06-07 02:59
Basically, the problem is that the last second of the chart is set once to a particular value which affects the entire file across all charts/difficulties. The chord density graph you see does not respect the final second value. It comes from the list of non empty rows. Since the chart becomes empty at a certain point, the graph pretends that is the end of the song and thus it gets stretched to appear like the notes are filling that section.

**Comment by poco0317** [comment] 2020-07-09 02:42
fixed by #827 and then 1f44dae42faf1251450596d6f0f4ed70390ce419 and 97d16111585f55d1aae35fdc8ad43db2932ad1bc
but theres a thing with preview looping that isnt fixed but will be eventually
follow #587

**Closed by poco0317** 2020-07-09 02:42 UTC
Labels: Priority: Low, Type: Bug
