### ISSUE TITLE
Delete the cache and relaunch the game causes crash

### ISSUE THREAD

**Issue by wlq1997** [etternagame/etterna#404] opened 2018-12-09 13:03 UTC
Crash reason: Access Violation

Unknown thread
        ragefiledriverdirecthelpers.cpp:230 F:/Etterna/Songs/Knit's Favorite Collection/02/*
        ragefiledriverdirecthelpers.cpp:230 F:/Etterna/Songs/Suomi 100/downfall (Wh1teh)/*
        ragefiledriverdirecthelpers.cpp:230 F:/Etterna/Songs/Knit's Favorite Collection/16warz/*
        ragefiledriverdirecthelpers.cpp:230 F:/Etterna/Songs/877xe/.357 Magnum/*
        ragefiledriverdirecthelpers.cpp:230 F:/Etterna/Songs/Dingles Finale/Smoke Bomb (Dingles)/*
Thread: Main thread
        ragefiledriverdirecthelpers.cpp:230 F:/Etterna/Songs/You're Streaming Again/*
        ragefiledriverdirecthelpers.cpp:230 F:/Etterna/Songs/Yume's 1st Restart Pack/*
        ragefiledriverdirecthelpers.cpp:230 F:/Etterna/Songs/Yume's 2nd A Half Pack/*
        ragefiledriverdirecthelpers.cpp:230 F:/Etterna/Songs/Zero kara Hajimeru Stepmania/*
        ragefiledriverdirecthelpers.cpp:230 F:/Etterna/Songs/Zinowo/*
Thread: Decode thread
Thread: Mixer thread
Thread: Music thread
d1a85bf2: Etterna!d16d0000

Static log:
Etterna0.64-git-4c0339daf4
Compiled 20181205 @ 03:26:12 (build 4c0339daf4)
Log starting 2018-12-08 20:58:12
	Verbosity: 1
Windows 6.2 (Win8) build 9200 []
WARNING: Unmatched 3 in "0003"
WARNING: Unmatched 3 in "2123"

Partial log:
00:16.419: Song file "/Songs/4k osumania dan/4K 9th Dan v2 (9th Dan) [Shoegazer]/4K 9th Dan v2.sm" has an unexpected value named "ATTACKS".
00:16.437: Song '/Songs/osu ranked/152065 Ras - STAGER [no video]/' points to a music file that doesn't exist, found music file 'bass01 (1).wav'
00:16.437: Format wav failed: Not a WAV file
00:16.437: Format mp3 failed: Failed to read any data at all
00:16.444: Sound file "" is really oga.
00:16.535: Song file "/Songs/4k osumania dan/4K Luminal v2 (Luminal) [Shoegazer]/4K Luminal v2.sm" has an unexpected value named "ATTACKS".
00:16.655: Song file "/Songs/4k osumania dan/4K Tachyon v3 (Tachyon v3) [snoverpk]/4K Tachyon v3.sm" has an unexpected value named "ATTACKS".
00:16.693: Song file "" has no BPM segments, default provided.
00:16.693: Song '/Songs/osu ranked/153316 DJ Genericname - Dear You [no video]/' points to a music file that doesn't exist, found music file 'Dear You.mp3'
00:16.791: Loaded 12 songs from "Songs/4k osumania dan"

0.60 can still relaunch the game, crash started from 0.61

**Comment by MinaciousGrace** [comment] 2018-12-09 22:05
it's almost certainly a file or pack with some unusual structure or format, possibly the osu loader? Clear cache again and move the packs around the 4k osumania dan out of your songs folder and see if it loads, if not, move about the first half of them out

i don't really remember offhand what changed with song load from 0.6 to 0.61 but if you could pinpoint the cause of the crash and send it we can fix it

**Comment by wlq1997** [comment] 2018-12-11 02:34
> it's almost certainly a file or pack with some unusual structure or format, possibly the osu loader? Clear cache again and move the packs around the 4k osumania dan out of your songs folder and see if it loads, if not, move about the first half of them out
> 
> i don't really remember offhand what changed with song load from 0.6 to 0.61 but if you could pinpoint the cause of the crash and send it we can fix it

I think the "osu ranked" pack caused the problem, but  i really have no idea what the cause was. Anyway, it's not a so big problem i think.

**Comment by MinaciousGrace** [comment] 2018-12-11 02:51
in that case it's most likely fixed by 887407008e24adc85038766a21da5f2dc28841a3

**Closed by MinaciousGrace** 2018-12-11 02:51 UTC
