### ISSUE TITLE
Toasty image is too large and doesn't fully show or hide itself

### ISSUE THREAD

**Issue by Kangaroux** [etternagame/etterna#398] opened 2018-12-02 19:55 UTC
**Describe the bug**
The toasty image is significantly bigger than the original file. This causes it to not fully appear on the screen as well as not fully disappear

**To Reproduce**
1. Use [this image](https://i.imgur.com/lfaBm6V.png) as a toasty
2. Use a 16:9 aspect ratio (I'm at 2560x1440)
3. Get a toasty

**Expected behavior**
The toasty should:

- Be relatively the same size as the original asset file
- Fully appear on the screen
- Fully disappear from the screen

**Screenshots**
**On-screen**
![Toasty shown](https://user-images.githubusercontent.com/2302541/49344160-b254a900-f641-11e8-9bfc-e701e626fa42.png)

**Off-screen**
![Toasty hidden](https://user-images.githubusercontent.com/2302541/49344156-acf75e80-f641-11e8-9c1d-dc6774cd985f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.64.0

**Additional context**

**Comment by nico-abram** [comment] 2018-12-10 23:49
Wait so you want the game to resize the image/scale it to be the same size as the original?

**Comment by Kangaroux** [comment] 2018-12-11 00:34
@nico-abram That's what I would expect. Just enforce some kind of max size and then scale the image if any of its dimensions exceed that max size. Otherwise you need to make the image really small and it looks super blurry.

**Comment by nico-abram** [comment] 2018-12-11 00:45
Ye, that should be a one liner in lua. Before doing it I'll around what other people think. I'm not 100% sure that's the best way to handle it.

**Comment by Kangaroux** [comment] 2018-12-11 00:49
@nico-abram The root of the issue is that if I want an image to be say 400px wide I need to make it 100px so etterna can scale it back up which means your image looks like shit. Ideally just make the toasty customizable like the other UI elements so people can make it whatever size they want.

**Comment by nico-abram** [comment] 2018-12-11 00:56
`Ideally just make the toasty customizable like the other UI elements so people can make it whatever size they want.`
Yeah that's what i was thinking. However, I'm not sure if the best way to go about that is:
1) Make it a lua file, so it has complete freedom
2) Make it an ini config file with stuff like scaling, movement, etc

I'd personally prefer 1, however I feel like most noteskins would have the exact same lua file, so I think it'd need some kind of fallback system to a default (Like noteskins). Currently, toasties aren't even "selectable" ingame, so there's quite a bit of work to do on them.

**Comment by MinaciousGrace** [comment] 2019-05-29 18:54
this _is_ the expected behavior

everything in the game is resized as you change the window size in order to preserve the proportional size of elements, there is no reason the toasty animation should act differently

the theme is set to an "intended" resolution of 480 (legacy setting, obviously not ideal) so when you run at 1440 you are upscaling everything by 480/270, since that is the proportional space it would take up on the y axis at the "intended" settings

modifying a single element to behave differently from all other elements is obviously not a good idea, and having a bunch of opaque code on the game end to try to figure out what the user intended to do and overriding what they might intentionally want to do would create more confusion than it would resolve and is also basically how stepmania got where it was in the first place, so we aren't going to do that

however toasties shouldn't be rendered after they've animated regardless of whether or not they are still on the screen, and that is fixed by 71232430058fc225ca6fae5cbcf50813f3b60b6f

ideally each toasty would have its own lua script and the solution would be to either resize the image (or use a smaller base image, remember it was intended for stuff 32x32) before you use  it, or downscale the loaded sprite in lua with a zoomto command, either way this responsibility is the user's

**Closed by MinaciousGrace** 2019-05-29 18:54 UTC
Labels: Good First Issue, Language: Lua, Priority: Low, Type: Bug
