### ISSUE TITLE
Constant Desync/Stuttering Issues During Gameplay

### ISSUE THREAD

**Issue by ghost** [etternagame/etterna#437] opened 2019-02-10 21:52 UTC
Video constantly desyncs from song audio during low impact play on sub-10 difficulty charts. Not to mention it also stutters more than an autistic child with a lisp.

Also multiple game crashes caused by sound reader when using OGG files. mp3 just floats away as i play.

**Comment by poco0317** [comment] 2019-02-10 21:56
Can I have some good examples of files with this issue?

**Comment by RyTak** [comment] 2019-02-10 21:58
Literally anything from SMO that isnt pre-parsed by your environment.

**Comment by TheROPFather** [comment] 2019-02-10 22:03
Gonna need some specific examples.

**Comment by poco0317** [comment] 2019-02-10 22:03
I'm not sure what you mean by pre-parsed. The most we've done is delete bloated stuff from packs, and that concerns EO itself, not Etterna. This is a game issue. I need specific examples.

**Comment by RyTak** [comment] 2019-02-10 22:06
ECS7 Qualifiers pack, Propane Nightmares [15], after the first run, the game stutters, then desyncs by 30ms. It happens any time there is a VPF spike in engine.

**Comment by TheROPFather** [comment] 2019-02-10 22:07
There is no 7 on SMO?

**Comment by RyTak** [comment] 2019-02-10 22:16
http://groovestats.com/ECS7/download/ECS7.zip

**Comment by TheROPFather** [comment] 2019-02-10 22:17
That file isn't under 10....

Also I don't want to play 10 minutes of something, do you have an example from a relevant pack?

**Comment by RyTak** [comment] 2019-02-10 22:19
Relevant to spread players? Nope. But this issue exists for anyone trying to run etterna on a pad level use. And dont give me shit about "but we don't advertise for pad play", thanks TriHex.

**Comment by TheROPFather** [comment] 2019-02-10 22:20
Nobody was giving you shit, but uh. A file from another pack would be useful, basically one that isn't going to require me to play for 10 minutes to test.

Also you stated it was files under 10, but provided a 16 - I don't mind that level, but yea.

**Comment by RyTak** [comment] 2019-02-10 22:21
The issue also occurs in Jayce's "Feel The Notes" pack. I've had the same issue with every chart in that pack.

**Comment by TheROPFather** [comment] 2019-02-10 22:32
OK, I've managed to reproduce this. I don't know how, but we can look into this - thanks for bringing it to our attention.

**Comment by poco0317** [comment] 2019-02-10 22:32
It's a legitimate issue. I didn't manage to reproduce, but I'll look into it.

**Comment by nico-abram** [comment] 2019-02-10 22:33
I can't find "Feel The Note" on https://search.stepmaniaonline.net/

**Comment by RyTak** [comment] 2019-02-10 22:36
Alright. Good luck fam. Closing issue now that it's known.

**Comment by MinaciousGrace** [comment] 2019-02-10 23:01
did you expect us to intentionally not fix something despite being provided the issue, source and examples?

we'd have to be stepmania to do that

opening until a commit solves it

**Comment by RyTak** [comment] 2019-02-10 23:17
Yeah, I gotta agree with you there. Neither of us are Stepmania. You guys are Project Etterna, we're Team Rizu. So that I can agree on :P

**Comment by nico-abram** [comment] 2019-02-10 23:19
If you have any other input on this issue, I{d apprecciate it. Thanks for the report.

**Comment by RyTak** [comment] 2019-02-10 23:26
If I find anything, I'll let you guys know. Our code differences are pretty wide now, so pinpointing the issue in the code here might take longer than expected.

**Comment by MinaciousGrace** [comment] 2019-02-11 00:25
ok im having trouble reproducing this so can i get some info

any hardware info you think is relevant?
os?
vsync? if not whats your general gameplay fps?
release build or develop?
ssd or hdd for songs folder?

**Comment by nico-abram** [comment] 2019-02-11 00:27
It might be useful to know if the stutter also happens on previews, or just gameplay

**Comment by RyTak** [comment] 2019-02-11 01:21
The stutter happens with vsync off, release install client, SSD install, all settings default except visual delay at +25ms. Running in OpenGL mode.

Drive load spikes are noticed when in song wheel. Same behavior causing the issue in gameplay, resulting in desync.

**Comment by nico-abram** [comment] 2019-02-11 01:41
Are you on linux?

**Comment by RyTak** [comment] 2019-02-11 01:45
Win10 x64

**Comment by ael224** [comment] 2019-05-22 13:16
100%  have this issue watch  any YT recording of the game you will see the stutter prefs watch etiennes  channel and it should become obvious

**Comment by TheROPFather** [comment] 2019-05-22 16:27
Uh, that's a different issue from the one brought up here. Etienne and others suffer from the microstutters that most players get, we're also looking into that however this issue was for a very specific stutter bug.

**Comment by bluebandit21** [comment] 2021-04-01 18:24
Did some forensic work here and found something kind of interesting.

The .sms of the Feel The Notes pack have the line `#TICKCOUNT:0.000=2;` present in nearly all of the charts.

Since I haven't ever seen that property before, I looked through my entire song library (which is decently large; 5731 songs), and only found 3 other instances of that field in any of them outside of that pack. 

Given how rare this attribute is, and the fact that every chart in Feel The Notes had it, I have to wonder if it's potentially related.
It's also entirely possible that this is a red herring and has absolutely nothing to do with the issue.

*However*, Propane Nightmares from ECS Qualifiers does not have this attribute set, so that can't solely be the cause of this issue, if it is the cause for Feel The Notes.


The other three songs from my collection that contain this attribute are below, in case we want to do further investigation as to whether they do or don't also have the aforementioned stutters.

/Songs/midare megapack 4/(HST) HST's OP -penance-/hst.sm:#TICKCOUNT:0.000=2;
/Songs/the Leftovers 3/minefield surfing  (Windoze)/[Speed Changes] - minefield surfing.sm:#TICKCOUNT:0.000=2;
/Songs/FFR Community Pack Novice Files Compilation/Poseidon (Kors K Mix) (Gameoson)/poseidon.sm:#TICKCOUNTS:0.000=2

**Comment by poco0317** [comment] 2021-04-01 18:34
In Gameplay, tickcount is fully irrelevant in the current game and the issue persists. Tickcount code still exists in gameplay but is never executed because we hardcoded it to be disabled for every style and every game.

**Comment by MinaciousGrace** [comment] 2023-07-12 00:38
the issue being described has been unable to be replicated by anyone looking at the issue or any general player in the last 4.5 years so

user error is going to be assumed

**Closed by MinaciousGrace** 2023-07-12 00:38 UTC
Labels: Type: Bug, Priority: High
