### ISSUE TITLE
Sometimes downloaded packs are not shown as downloaded in ingame pack downloader

### ISSUE THREAD

**Issue by senya0** [etternagame/etterna#848] opened 2020-07-15 20:09 UTC
**Describe the bug**
title. seems to keep happening to me with the kaiten and mina packs

**To Reproduce**
1. download packs from ingame dl
2. hopefully see error

**Expected behavior**
pack downloader should recognize what packs you already have downloaded and installed

0.70.2 w10 64bit

**Comment by nico-abram** [comment] 2020-07-15 20:53
If I recall correctly downloaded packs are checked by comparing the pack names. Do those packs have the same title in the packlist/EO as the name of the pack folder in your songs folder @senya0 ? If so, this bug is to be expected. The current "downloaded pack" check was meant to be a quick and dirty thing that would mostly work

**Comment by senya0** [comment] 2020-07-16 03:48
The names were slightly different. The issue seems to be that the default name of the pack and the name that the downloader checks for seem to be slightly different, but it's up to the pack uploader to fix those.

**Comment by nico-abram** [comment] 2022-05-14 14:58
Going to close this for now as "by design"

I'm not entirely sure what the best way to handle this would be, and comparing by name seems to mostly work fine

**Closed by nico-abram** 2022-05-14 14:58 UTC
Labels: Type: Bug, Priority: Low
