### ISSUE TITLE
0.60.0 - Mac High Sierra Error

### ISSUE THREAD

**Issue by igormclven** [etternagame/etterna#241] opened 2018-08-19 03:25 UTC
```
Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/###/Desktop/Etterna-0.60-git-0e213f9/Etterna.app/Contents/MacOS/Etterna-release-symbols
  Reason: image not found
Abort trap: 6
logout
```
I'm getting this error when running the latest version of etterna.

**Comment by nico-abram** [comment] 2018-08-19 03:36
Hi!
Thanks for the report.
Could you try installing opensll or libssl or openssl (Or w.e its called)?
Iirc it should be `brew install openssl`(Or `brew install libssl` (Or `brew install libssl`))
Sorry, I'm not a mac person and i dont have a mac. If this doesnt work rop might be able to help more (With some luck he'll see this in <48hs)

**Comment by TheROPFather** [comment] 2018-08-19 11:29
Hi, 

It is likely that you will need to run the following commands in your terminal.

`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

This installs brew, which is a package manager for OSX.

`brew install openssl`
`brew install libuv`

This should fix your issue. If after this you get an error loading the game that says No Noteskins, run the following command in your terminal.

`sudo xattr -dr com.apple.quarantine /path/to/Etterna`

This should be everything needed, I will keep this open since the libraries should be included.

**Comment by igormclven** [comment] 2018-08-19 13:34
Thanks for the info, I will try to do that.

**Comment by TheKamilia** [comment] 2018-09-24 16:19
> Thanks for the info, I will try to do that.

did it work?

**Comment by kcsongor** [comment] 2018-10-03 19:20
@TheKamilia I had the exact same issue (on Mojave), and I can confirm that @TheROPFather's instructions fixed the issue

**Comment by jackcogdill** [comment] 2018-10-10 21:21
I have the same issue with `openssl` and `libuv`. I have these libraries installed from Macports, not Homebrew.

**Comment by martensm** [comment] 2019-03-16 02:43
Closing since this is resolved.

**Closed by martensm** 2019-03-16 02:43 UTC
Labels: Priority: High, Type: Bug
