### ISSUE TITLE
一定間隔でのFPSドロップ

### ISSUE THREAD

**Issue by ROM256** [etternagame/etterna#635] opened 2019-09-23 09:25 UTC
プレイ中突然、一定間隔でティアリングします。再起動しても治らない

**Comment by poco0317** [comment] 2019-09-23 23:58
I apologize; as far as I am aware nobody on the dev team can speak Japanese so I must rely on translation software.

Are you referring to FPS drops? Or is it screen tearing? Screen tearing can sometimes be fixed with "Vsync on."
Is it possible that you can provide more information or a video recording of the problem?

**Comment by ROM256** [comment] 2019-09-24 00:17
Occasional symptoms occur Tiering
Even if you record, FPS may tear instead of drop
google translate

**Comment by poco0317** [comment] 2019-09-24 00:27
Try any of the following options that might reduce the problems:

- Play windowed.
- Lower the resolution of Etterna.
- Make sure Etterna is the only program opened.
- Log out while playing.
- Limit the maximum framerate of the game.
You can find this in `/Save/Preferences.ini`
Change `FrameLimit=` and `FrameLimitGameplay=` to a lower number.

If possible, can you attach this file to a reply after playing some songs? `/Logs/log.txt`

Let me know if anything helps.

**Comment by ROM256** [comment] 2019-09-24 00:52
[log.txt](https://github.com/etternagame/etterna/files/3644700/log.txt)

**Comment by ROM256** [comment] 2019-09-24 00:52
[log.txt](https://github.com/etternagame/etterna/files/3644701/log.txt)
[userlog.txt](https://github.com/etternagame/etterna/files/3644702/userlog.txt)
[info.txt](https://github.com/etternagame/etterna/files/3644703/info.txt)

**Comment by poco0317** [comment] 2019-09-24 03:35
Try changing video renderers:

Close the game.
Find `/Save/Preferences.ini`
Change `VideoRenderers=d3d, opengl` -> `VideoRenderers=opengl, d3d`
Open the game and see if that fixed it.

**Comment by ROM256** [comment] 2019-09-24 06:54
Changing the video renderer or restarting does not help.
It happens irregularly and I don't know how to deal with it.

**Comment by ROM256** [comment] 2019-09-24 10:01
Even if FrameLimit in Preferences.ini is set to 144 to match the monitor, the display of FPS is 143 FPS and 1 frame is missing. It seems to stop for a moment. Is this the cause?
If you double it to 288, it only comes out at 250 fps, and it doesn't flicker, but it stops for a moment when time passes like before.

**Comment by ROM256** [comment] 2019-09-24 10:16
Set FrameLimit in Preferences.ini to 144 to match your monitor. The FPS display is 143 FPS and 1 frame short. It seems to stop for a moment.
If you double it to 288, it stops for a moment when there is time when only 250 fps is displayed.
![無題](https://user-images.githubusercontent.com/53605035/65503392-cedb0e00-deff-11e9-8955-b14a5a6bf12a.png)

**Comment by ROM256** [comment] 2019-10-13 23:41
Stuttering Issues During Gameplay. Same behavior causing the issue in gameplay, resulting in desync.

**Comment by poco0317** [comment] 2019-10-13 23:46
When you have the stuttering issues, does it feel like the monitor's refresh rate is dropping or is it like the game is actually stuttering for longer periods of time? 

Odd refresh rate issues can be caused by Windows 10's notifications or taskbar. When icons flash in the Windows taskbar (yellow for a Discord message, for example) this can cause the refresh rate of the game to drop if playing on windowed mode.

Stuttering causing desync sounds like the stuttering is a sustained freeze. Freezing for several seconds has been known to somehow mess with the sync of the game. Restarting the game is the only simple way to fix it when that happens.

**Comment by ROM256** [comment] 2019-10-14 03:24
I feel that the refresh rate of the monitor is low

**Comment by ROM256** [comment] 2019-10-14 03:24
I feel like the monitor refresh rate is slowing down.

**Comment by ROM256** [comment] 2020-01-18 01:27
[crashinfo.txt](https://github.com/etternagame/etterna/files/4079828/crashinfo.txt)

**Comment by ROM256** [comment] 2020-01-28 09:23
Turning Anisotropic Sample Optimization On and Off Eliminates Flicker

**Comment by poco0317** [comment] 2020-04-11 00:04
This issue may possibly be solved by a recent Windows update.

**Comment by nico-abram** [comment] 2022-05-14 14:25
@ROM256 Are you still experiencing this issue?

**Comment by ROM256** [comment] 2022-05-14 22:49
Resolved.

**Closed** 2022-05-14 22:52 UTC
Labels: Type: Question, Platform: Windows
