### ISSUE TITLE
Game crashed after completing song

### ISSUE THREAD

**Issue by M4k4s** [etternagame/etterna#603] opened 2019-07-26 08:47 UTC
Describe the bug
After completing the song, game crashed because system can't find Etterna.vdi debug file and display Undhadled Microsoft C++ exception. 

1. Install latest version of Etterna (0.66)
2. Manualy add songs to "Songs" folder in C:\Games\Etterna\Songs
3. Lunch Etterna.exe
4. In menu select Game Start
5. Play the added song
6. Complete the song
7. See error

Expected behavior
I expected the results screen with scores

Desktop:
 - OS: Windows 10 Home
 - Version 1803
 - 64bit

Additional context:
Etterna or the installer probably doesn't create .vdi debug file for debbuging songs wich are created in StepMania 5

**Comment by poco0317** [comment] 2019-07-26 08:49
This is most likely a duplicate of #589 which is an issue where the cause has been found, and we are working on a fix.
However, since you say "Unhandled C++ Exception" it may be something else.
You need to give the whole crashlog. This crash actually has nothing to do with the vdi missing. That does not affect anything.

**Comment by M4k4s** [comment] 2019-07-26 16:31
[crashinfo.txt](https://github.com/etternagame/etterna/files/3436621/crashinfo.txt)
Here is crash info

**Comment by poco0317** [comment] 2019-07-26 18:44
Note for anyone checking into this: based on the crashinfo the issue is within this section of code 
https://github.com/etternagame/etterna/blob/cce9555823b0e2e5fdcaa92b632f42d27a41db94/src/Etterna/Models/Misc/StageStats.cpp#L672-L693

**Comment by poco0317** [comment] 2019-10-30 08:45
Crash cause found: https://github.com/etternagame/etterna/blob/cce9555823b0e2e5fdcaa92b632f42d27a41db94/src/Etterna/Models/Misc/StageStats.cpp#L681-L682

On new sessions when not forcefully disconnected from SMonline (or if you connect manually but dont enter multiplayer) the bool here is true. ReportHighScore is useful for only Multiplayer. The connection to multiplayer can go bad (?) and through its process, ReportHighScore throws a C++ Exception from within websocketpp
https://github.com/etternagame/etterna/blob/cce9555823b0e2e5fdcaa92b632f42d27a41db94/extern/websocketpp/websocketpp/impl/endpoint_impl.hpp#L177

... So either we handle this exception or we find a way to not have that bool incorrectly true.

**Comment by poco0317** [comment] 2019-11-29 11:01
fixed in 655ea086cf18cc565fdedae17f7351fa930b573b

**Closed by poco0317** 2019-11-29 11:01 UTC
Labels: Priority: Medium, Type: Bug
